{"name": "Login Fallido - Credenciales Inválidas (Usuario Inexistente)", "status": "passed", "description": "Verifica que el sistema rechaza credenciales inválidas cuando el usuario no existe.", "steps": [{"name": "POST a /login con usuario inexistente", "status": "passed", "start": 1747074852012, "stop": 1747074853080}, {"name": "Verificar permanencia en página de login (200) y mensaje de error", "status": "passed", "start": 1747074853080, "stop": 1747074853080}, {"name": "Verificar que el usuario NO está autenticado en la sesión", "status": "passed", "start": 1747074853080, "stop": 1747074853082}], "start": 1747074852012, "stop": 1747074853082, "uuid": "1c3c5381-09aa-4933-aa45-d4686f54a09b", "historyId": "6a1f1aff62a24f21af906abdc17d2da6", "testCaseId": "6a1f1aff62a24f21af906abdc17d2da6", "fullName": "financialSearch.tests.TestAuthentication#test_login_invalid_credentials_nonexistent_user", "labels": [{"name": "tag", "value": "negative"}, {"name": "feature", "value": "Sistema de Autenticación"}, {"name": "severity", "value": "normal"}, {"name": "tag", "value": "auth"}, {"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "financialSearch"}, {"name": "suite", "value": "tests"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "nickell01"}, {"name": "thread", "value": "12784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "financialSearch.tests"}]}